<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:template match="/">
        <html>
        <head>
            <title>XML Sitemap</title>
            <style>
                body { font-family: Arial, sans-serif; background-color: #f9f9f9; padding: 20px; }
                h1, p { color: #333; }
                table { width: 100%; border-collapse: collapse; background: white; margin-top: 20px; }
                th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
                th { background-color: #f4f4f4; font-weight: bold; }
                a { color: #0275d8; text-decoration: none; }
                a:hover { text-decoration: underline; }
            </style>
        </head>
        <body>
            <h1>XML Sitemap</h1>
            <p>Generated by Yoast SEO, this is an XML Sitemap, meant for consumption by search engines.</p>
            <p>You can find more information about XML sitemaps on <a href="https://www.sitemaps.org">sitemaps.org</a>.</p>
            <p>This XML Sitemap Index file contains 4 sitemaps.</p>
            <table>
                <tr>
                    <th>Sitemap</th>
                    <th>Last Modified</th>
                </tr>
                
                <tr>
                    <td><a href="https://www.dkglabs.com/#features">https://www.dkglabs.com/#features</a></td>
                    <td>2025-01-19T09:00:33+00:00</td>
                </tr>
                <tr>
                    <td><a href="https://www.dkglabs.com/#pricing">https://www.dkglabs.com/#pricing</a></td>
                    <td>2025-01-19T09:00:33+00:00</td>
                </tr>
                <tr>
                    <td><a href="https://www.dkglabs.com/#roadmap">https://www.dkglabs.com/#roadmap</a></td>
                    <td>2025-01-19T09:00:33+00:00</td>
                </tr>
                <tr>
                    <td><a href="https://www.dkglabs.com/#contact">https://www.dkglabs.com/#contact</a></td>
                    <td>2025-01-19T09:00:33+00:00</td>
                </tr>
            </table>
        </body>
        </html>
    </xsl:template>
</xsl:stylesheet>
